on:
  push:
    branches:
    - master

name: Google App Script Deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        clasprc-json-path: [~/.clasprc.json]
    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ./GoogleAppScript
      run: yarn install
    - name: Setup Google App Script .env
      working-directory: ./GoogleAppScript
      env:
        TARGET_SPREADSHEET_ID: ${{ secrets.TARGET_SPREADSHEET_ID }}
      run: |
        echo "TARGET_SPREADSHEET_ID=${TARGET_SPREADSHEET_ID}" >> ./.env
    - name: clasp creds
      env:
        CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      working-directory: ./GoogleAppScript
      run: echo "${CLASPRC_JSON}" >> ${{ matrix.clasprc-json-path }}
    - name: clasp undeploy all
      working-directory: ./GoogleAppScript
      run: yarn run undeploy:all
    - name: clasp deploy
      working-directory: ./GoogleAppScript
      run: yarn run deploy
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: GoogleAppScript/dist